import { test, expect, addresses } from './fixtures'

test('contributor applies and the poster assigns the applicant', async ({page,app}) => {
  await page.goto('/bounty/1'); await app.connect()
  await page.getByRole('textbox',{name:'Why you'}).fill('I can build an accessible explorer.')
  await page.getByRole('button',{name:'Apply for this bounty'}).click()
  await expect(page.getByRole('status')).toContainText('Application sent')
  await expect(page.getByText('You applied. The poster will assign someone.',{exact:true})).toBeVisible()
  expect(app.txs[0]!.messages[0]!.value).toMatchObject({func:'Apply',args:['1','I can build an accessible explorer.'],caller:addresses.worker})
  await app.setWallet(addresses.poster)
  await expect(page.getByRole('textbox',{name:"Contributor's address"})).toBeVisible()
  const application = page.locator('li').filter({hasText:'I can build an accessible explorer.'}).filter({has:page.getByRole('button',{name:'Assign',exact:true})})
  await application.getByRole('button',{name:'Assign',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Assigned.')
  expect(app.txs[1]!.messages[0]!.value).toMatchObject({func:'Assign',args:['1',addresses.worker]})
  await expect(page.getByText('In progress',{exact:true})).toBeVisible()
})

test('poster validates a direct assignment and can cancel for a refund', async ({page,app}) => {
  await page.goto('/bounty/1'); await app.connect(addresses.poster)
  const input = page.getByRole('textbox',{name:"Contributor's address"})
  await input.fill('bad-address')
  await expect(page.locator('form').filter({has:input}).getByRole('button',{name:'Assign',exact:true})).toBeDisabled()
  await input.fill(addresses.worker)
  await page.getByRole('button',{name:'Cancel and refund'}).click()
  await expect(page.getByText('Cancel this bounty?',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Keep bounty'}).click()
  expect(app.txs).toHaveLength(0)
  await page.getByRole('button',{name:'Cancel and refund'}).click()
  await page.getByRole('button',{name:'Confirm cancellation'}).click()
  await expect(page.getByRole('status')).toContainText('The escrow was refunded to you')
  await expect(page.getByText('Cancelled',{exact:true})).toBeVisible()
  expect(app.txs[0]!.messages[0]!.value).toMatchObject({func:'Cancel',args:['1']})
})

test('direct assignment signs the chosen address', async ({page,app}) => {
  await page.goto('/bounty/1'); await app.connect(addresses.poster)
  const form = page.locator('form').filter({has:page.getByRole('textbox',{name:"Contributor's address"})})
  await form.getByRole('textbox').fill(addresses.worker)
  await form.getByRole('button',{name:'Assign',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Assigned.')
  expect(app.txs[0]!.messages[0]!.value.args).toEqual(['1',addresses.worker])
})

test('worker delivers, reviewer requests changes, worker resubmits, reviewer releases payment', async ({page,app}) => {
  await page.goto('/bounty/2'); await app.connect()
  const first = page.getByRole('list',{name:'Milestones'}).getByRole('listitem').first()
  await first.getByRole('button',{name:'Submit work'}).click()
  await first.getByRole('textbox',{name:'Link to the work'}).fill('https://github.com/gnolang/gno/pull/100')
  await first.getByRole('button',{name:'Submit for review'}).click()
  await expect(first.getByText('In review',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Step back'})).toBeDisabled()
  expect(app.txs[0]!.messages[0]!.value.args).toEqual(['2','1','https://github.com/gnolang/gno/pull/100'])
  await app.setWallet(addresses.reviewer)
  await first.getByRole('button',{name:'Request changes',exact:true}).click()
  await first.getByRole('textbox',{name:'What needs to change'}).fill('Add keyboard navigation.')
  await first.locator('form').getByRole('button',{name:'Request changes',exact:true}).click()
  await expect(first.getByText('Changes requested:',{exact:true})).toBeVisible()
  await app.setWallet(addresses.worker)
  await first.getByRole('button',{name:'Resubmit work'}).click()
  await first.getByRole('textbox',{name:'Link to the work'}).fill('https://github.com/gnolang/gno/pull/101')
  await first.getByRole('button',{name:'Submit for review'}).click()
  await app.setWallet(addresses.reviewer)
  await first.getByRole('button',{name:'Approve',exact:true}).click()
  await expect(first.getByText('Paid',{exact:true})).toBeVisible()
  expect(app.txs.map(t => t.messages[0]!.value.func)).toEqual(['Submit','RequestChanges','Submit','Approve'])
  expect(app.get(2).paidOut).toBe(50_000_000)
})

test('quorum collects distinct approvals before releasing funds', async ({page,app}) => {
  app.get(3).reviewers.push(addresses.reviewer2); app.get(3).quorum = 2
  await page.goto('/bounty/3'); await app.connect(addresses.reviewer)
  const first = page.getByRole('list',{name:'Milestones'}).getByRole('listitem').first()
  await first.getByRole('button',{name:'Approve',exact:true}).click()
  await expect(first.getByText('1 of 2 approvals',{exact:true})).toBeVisible()
  await expect(first.getByText('You approved this.',{exact:true})).toBeVisible()
  await expect(first.getByRole('button',{name:'Approve',exact:true})).toHaveCount(0)
  await app.setWallet(addresses.reviewer2)
  await first.getByRole('button',{name:'Approve',exact:true}).click()
  await expect(first.getByText('Paid',{exact:true})).toBeVisible()
  expect(app.get(3).paidOut).toBe(50_000_000)
})

test('worker opens a dispute and council settles a partial payout', async ({page,app}) => {
  await page.goto('/bounty/3'); await app.connect()
  const first = page.getByRole('list',{name:'Milestones'}).getByRole('listitem').first()
  await first.getByRole('button',{name:'Open a dispute'}).click()
  await first.getByRole('textbox',{name:'Why this needs an arbiter'}).fill('The delivered scope was agreed.')
  await first.getByRole('button',{name:'Open dispute',exact:true}).click()
  await expect(first.getByText('Disputed',{exact:true})).toBeVisible()
  await app.setWallet(addresses.council)
  await first.getByRole('button',{name:'Settle dispute',exact:true}).click()
  const slider = first.getByRole('slider')
  await expect(slider).toHaveValue('100')
  await slider.fill('75')
  await expect(first.getByText("Contributor's share: 75%",{exact:true})).toBeVisible()
  await first.getByRole('textbox',{name:'Ruling',exact:true}).fill('Most of the scope is complete.')
  await first.getByRole('button',{name:'Settle and pay out'}).click()
  await expect(first.getByText('Split by arbiter',{exact:true})).toBeVisible()
  await expect(first.getByText(/75% to the contributor/)).toBeVisible()
  expect(app.txs[1]!.messages[0]!.value).toMatchObject({func:'Resolve',args:['3','1','7500','Most of the scope is complete.']})
})

test('named arbiter can settle a dispute with the default full share', async ({page,app}) => {
  app.get(4).councilArbitrated = false; app.get(4).arbiter = addresses.visitor
  await page.goto('/bounty/4'); await app.connect(addresses.visitor)
  await page.getByRole('button',{name:'Settle dispute',exact:true}).click()
  await expect(page.getByRole('slider')).toHaveValue('100')
  await page.getByRole('button',{name:'Settle and pay out'}).click()
  await expect(page.getByRole('status')).toContainText('Dispute settled.')
  expect(app.txs[0]!.messages[0]!.value.args).toEqual(['4','1','10000',''])
})

test('workers can step back and posters can reclaim overdue work', async ({page,app}) => {
  await page.goto('/bounty/2'); await app.connect()
  await page.getByRole('button',{name:'Step back'}).click()
  await expect(page.getByRole('status')).toContainText('You stepped back.')
  expect(app.txs[0]!.messages[0]!.value.func).toBe('Unassign')
  await page.goto('/bounty/7'); await app.setWallet(addresses.poster)
  await expect(page.getByRole('button',{name:'Reopen for someone else'})).toBeDisabled()
  app.get(7).assignedAt = '2020-01-01T00:00:00Z'
  await page.reload()
  await page.getByRole('button',{name:'Reopen for someone else'}).click()
  await expect(page.getByRole('status')).toContainText('Bounty reopened.')
})

test('role restrictions hide unauthorized actions and completed work is read-only', async ({page,app}) => {
  await page.goto('/bounty/1'); await app.connect(addresses.reviewer)
  await expect(page.getByRole('button',{name:'Apply for this bounty'})).toHaveCount(0)
  await expect(page.getByText(/you can't apply for it/)).toBeVisible()
  await app.setWallet(addresses.council)
  await expect(page.getByRole('button',{name:'Apply for this bounty'})).toHaveCount(0)
  await page.goto('/bounty/3'); await app.setWallet(addresses.visitor)
  await expect(page.getByRole('button',{name:'Approve',exact:true})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Open a dispute'})).toHaveCount(0)
  await page.goto('/bounty/5'); await app.setWallet(addresses.worker)
  await expect(page.getByRole('button',{name:'Submit work'})).toHaveCount(0)
  await expect(page.getByText(/This bounty is completed/)).toBeVisible()
  expect(app.txs).toHaveLength(0)
})

test('wallet pending state prevents duplicate writes and surfaces realm failures', async ({page,app}) => {
  await page.goto('/bounty/1'); await app.connect()
  let release!: () => void; app.txGate = new Promise<void>(resolve => release = resolve)
  const button = page.getByRole('button',{name:'Apply for this bounty'})
  try { await button.click(); await expect(page.getByRole('button',{name:'Sending application…'})).toBeDisabled(); expect(app.txs).toHaveLength(1) }
  finally { app.txGate = null; release() }
  await expect(page.getByRole('status')).toContainText('Application sent.')
  await page.goto('/bounty/2')
  app.nextTxError = 'A milestone is awaiting review.'
  await page.getByRole('button',{name:'Step back'}).click()
  await expect(page.getByRole('alert')).toContainText('A milestone is awaiting review.')
})

test('all approved milestones complete a bounty and clear the escrow', async ({page,app}) => {
  app.get(3).milestones[1] = {...app.get(3).milestones[1]!,status:'submitted',worker:addresses.worker,approvals:[],submission:'gno.land/r/demo/toolkit'}
  await page.goto('/bounty/3'); await app.connect(addresses.reviewer)
  await page.getByRole('button',{name:'Approve',exact:true}).first().click()
  await expect(page.getByRole('list',{name:'Milestones'}).getByText('Paid',{exact:true})).toHaveCount(1)
  await page.getByRole('button',{name:'Approve',exact:true}).click()
  await expect(page.getByText('Completed',{exact:true})).toBeVisible()
  await expect(page.getByRole('list',{name:'Milestones'}).getByText('Paid',{exact:true})).toHaveCount(2)
  expect(app.get(3).escrowed).toBe(0)
  expect(app.get(3).paidOut).toBe(app.get(3).total)
})

test('arbiter can refund an entire disputed milestone to the poster', async ({page,app}) => {
  await page.goto('/bounty/4'); await app.connect(addresses.council)
  await page.getByRole('button',{name:'Settle dispute',exact:true}).click()
  await page.getByRole('slider').fill('0')
  await page.getByRole('textbox',{name:'Ruling',exact:true}).fill('No work was delivered.')
  await page.getByRole('button',{name:'Settle and pay out'}).click()
  await expect(page.getByRole('list',{name:'Milestones'}).getByText('Refunded',{exact:true})).toBeVisible()
  expect(app.txs[0]!.messages[0]!.value.args).toEqual(['4','1','0','No work was delivered.'])
  expect(app.get(4).paidOut).toBe(0)
})
