import { test, expect, addresses, bounty } from './fixtures'

test('overview presents real activity and leads to a bounty', async ({page, app}) => {
  await page.goto('/')
  await expect(page.getByRole('heading', {name: /Build something good/})).toBeVisible()
  await expect(page.getByRole('list', {name:'Bounties'})).toContainText('Build a better realm explorer')
  await expect(page.getByRole('list', {name:'Work records'})).toContainText('Explorer accessibility improvements')
  await expect(page.getByRole('definition').filter({hasText:'750'})).toBeVisible()
  await page.getByRole('link', {name:'Explore bounties', exact:true}).click()
  await expect(page).toHaveURL(/\/bounties$/)
  await page.getByRole('link', {name:'Build a better realm explorer, bounty 1'}).click()
  await expect(page.getByRole('heading', {name:'Build a better realm explorer',exact:true})).toBeVisible()
  await expect(page.getByRole('list', {name:'Milestones'})).toContainText('Implementation & docs')
  await expect(page.getByRole('heading', {name:'Your role'})).toBeVisible()
  expect(app.queries.some(q => q.includes('api/bounty/1'))).toBeTruthy()
})

test('board status and tag filters survive browser history', async ({page, app}) => {
  await page.goto('/bounties')
  const filters = page.getByRole('navigation', {name:'Filter by status'})
  await filters.getByRole('button', {name:'In progress',exact:true}).click()
  await expect(page.getByRole('list', {name:'Bounties'})).toContainText('Write the interrealm guide')
  await page.getByRole('textbox', {name:'Filter by tag'}).fill('#DOCS')
  await page.getByRole('button', {name:'Filter',exact:true}).click()
  await expect(page).toHaveURL(/status=active&tag=docs/)
  await expect(page.getByRole('list', {name:'Bounties'}).getByRole('listitem')).toHaveCount(2)
  await filters.getByRole('button', {name:'Completed',exact:true}).click()
  await expect(page.getByRole('heading', {name:'No bounties found'})).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('textbox', {name:'Filter by tag'})).toHaveValue('docs')
  await expect(page.getByRole('list', {name:'Bounties'}).getByRole('listitem')).toHaveCount(2)
  await page.getByRole('button', {name:'Clear filter'}).click()
  await expect(page.getByRole('textbox', {name:'Filter by tag'})).toHaveValue('')
  await expect(page.getByRole('list', {name:'Bounties'}).getByRole('listitem')).toHaveCount(4)
  expect(app.queries.some(q => q.includes('status=active&tag=docs'))).toBeTruthy()
})

test('board paginates, resets page on filtering, and normalizes invalid parameters', async ({page, app}) => {
  app.bounties = Array.from({length:25}, (_, i) => bounty(i + 10))
  await page.goto('/bounties?status=unknown&page=-3')
  await expect(page.getByRole('navigation', {name:'Filter by status'}).getByRole('button',{name:'Open',exact:true})).toHaveAttribute('aria-current','page')
  await expect(page.getByRole('list', {name:'Bounties'}).getByRole('listitem')).toHaveCount(20)
  await expect(page.getByRole('button', {name:'Newer'})).toBeDisabled()
  await page.getByRole('button', {name:'Older'}).click()
  await expect(page).toHaveURL(/page=2/)
  await expect(page.getByRole('list', {name:'Bounties'}).getByRole('listitem')).toHaveCount(5)
  await expect(page.getByRole('button', {name:'Older'})).toBeDisabled()
  await page.getByRole('button', {name:'Newer'}).click()
  await expect(page.getByRole('list', {name:'Bounties'}).getByRole('listitem')).toHaveCount(20)
  await page.getByRole('button', {name:'Older'}).click()
  await page.getByRole('textbox', {name:'Filter by tag'}).fill('docs')
  await page.getByRole('button', {name:'Filter',exact:true}).click()
  await expect(page).not.toHaveURL(/page=/)
  await expect(page.getByRole('list', {name:'Bounties'}).getByRole('listitem')).toHaveCount(13)
})

test('contributors link to profiles, work records, reviews and involved bounties', async ({page, app}) => {
  await page.goto('/contributors')
  await expect(page.getByRole('table')).toContainText('Seed reviewer')
  await page.locator(`table a[href="/u/${addresses.worker}"]`).click()
  await expect(page.getByRole('heading', {name:'Artisan',exact:true})).toBeVisible()
  await expect(page.getByRole('list', {name:'Work records'}).getByRole('listitem')).toHaveCount(2)
  await expect(page.getByText('GovDAO eligibility')).toBeVisible()
  const sections = page.getByRole('navigation', {name:'Profile sections'})
  await sections.getByRole('button', {name:'Reviews'}).click()
  await expect(page.getByRole('heading', {name:'No reviews on record yet'})).toBeVisible()
  await sections.getByRole('button', {name:'Bounties'}).click()
  await expect(page.getByRole('list', {name:'Bounties'})).toContainText('Your role: contributor')
  await sections.getByRole('button', {name:'Work',exact:true}).click()
  await page.getByRole('link', {name:'Explorer accessibility improvements, record 1'}).click()
  await expect(page.getByRole('heading', {name:'Explorer accessibility improvements'})).toBeVisible()
  await expect(page.getByText('+100 reputation',{exact:true})).toBeVisible()
  await page.getByRole('link', {name:'Bounty 5',exact:true}).click()
  await expect(page.getByRole('heading', {name:'Improve the faucet experience'})).toBeVisible()
  expect(app.queries.some(q => q.includes('kind=reviews'))).toBeTruthy()
})

test('record views show voided and arbitrated payment details', async ({page, app}) => {
  app.records[0]!.arbitrated = true
  app.records[0]!.shareBps = 7500
  await page.goto('/record/1')
  await expect(page.getByRole('heading', {name:'Settled by'})).toBeVisible()
  await expect(page.getByText(/75% of the milestone/)).toBeVisible()
  await page.goto('/record/2')
  await expect(page.getByRole('alert')).toContainText('Duplicate contribution')
  await expect(page.getByText('+0 reputation',{exact:true})).toBeVisible()
  await expect(page.getByRole('heading', {name:'Legacy toolkit implementation'})).toHaveClass(/line-through/)
})

test('how it works explains the lifecycle and scores', async ({page, app}) => {
  await page.goto('/how')
  await expect(page.getByRole('heading', {name:'A bounty, start to finish'})).toBeVisible()
  await expect(page.getByRole('table')).toContainText('Grandmaster')
  await expect(page.getByText('100',{exact:true})).toBeVisible()
  await expect(page.locator('pre')).toContainText('reputation.AssertScore')
  expect(app.queries.some(q => q.includes('/reputation:api/stats'))).toBeTruthy()
})

test('unknown routes and missing entities have useful recovery', async ({page, app}) => {
  await page.goto('/missing-route')
  await expect(page.getByRole('heading', {name:'Page not found',exact:true})).toBeVisible()
  await page.getByRole('link', {name:'Back to Guildhall'}).click()
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/bounty/999')
  await expect(page.getByRole('alert')).toContainText('There is no bounty #999')
  await page.goto('/record/999')
  await expect(page.getByRole('alert')).toContainText('There is no record #999')
  await page.goto('/u/invalid')
  await expect(page.getByRole('alert')).toContainText('That is not a g1 address')
  expect(app.queries.some(q => q.includes('api/profile/invalid'))).toBeFalsy()
})

test('profile work and reviews paginate and reset when changing sections', async ({page,app}) => {
  app.records = Array.from({length:24},(_,i) => ({...app.records[0]!,id:i+10,title:`Reviewed contribution ${i+10}`,reviewers:[addresses.worker]}))
  await page.goto(`/u/${addresses.worker}`)
  await expect(page.getByRole('list',{name:'Work records'}).getByRole('listitem')).toHaveCount(20)
  await page.getByRole('button',{name:'Older'}).click()
  await expect(page.getByRole('list',{name:'Work records'}).getByRole('listitem')).toHaveCount(4)
  await page.getByRole('navigation',{name:'Profile sections'}).getByRole('button',{name:'Reviews'}).click()
  await expect(page.getByText('Page 1',{exact:true})).toBeVisible()
  await expect(page.getByRole('list',{name:'Work records'}).getByRole('listitem')).toHaveCount(20)
})

test('profile address copying reports success and clipboard failures', async ({page,app}) => {
  await page.addInitScript(() => {
    Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async (text:string) => { (window as any).__copied = text }}})
  })
  await page.goto(`/u/${addresses.worker}`)
  await page.getByRole('button',{name:'Copy address'}).click()
  await expect(page.getByRole('status')).toHaveText('Address copied')
  expect(await page.evaluate(() => (window as any).__copied)).toBe(addresses.worker)
  await page.evaluate(() => { Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async () => {throw new Error('No clipboard permission')}}}) })
  await page.getByRole('button',{name:'Address copied'}).click()
  await expect(page.getByRole('alert')).toContainText('Could not copy')
  expect(app.txs).toHaveLength(0)
})
