import { test, expect, addresses, record, realmRoot, token } from './fixtures'

test('campaigns are listed, filtered and open to their claims', async ({page, app}) => {
  await page.goto('/')
  await expect(page.getByRole('list', {name: 'Campaigns'})).toContainText('Write about Guildhall')
  await page.getByRole('region', {name: 'Quick tasks, many hands'}).getByRole('link', {name: 'View all'}).click()
  await expect(page).toHaveURL(/\/campaigns/)
  const list = page.getByRole('list', {name: 'Campaigns'})
  await expect(list.getByRole('listitem')).toHaveCount(1)
  await expect(list).toContainText('1 of 100 paid · 98 left')
  await page.getByRole('navigation', {name: 'Filter by status'}).getByRole('button', {name: 'Closed', exact: true}).click()
  await expect(list).toContainText('Translate the onboarding page')
  await page.getByRole('navigation', {name: 'Filter by status'}).getByRole('button', {name: 'Open', exact: true}).click()
  await page.getByRole('link', {name: 'Write about Guildhall, campaign 1'}).click()
  await expect(page.getByRole('heading', {name: 'Write about Guildhall', exact: true})).toBeVisible()
  const claims = page.getByRole('list', {name: 'Claims'})
  await expect(claims.getByRole('listitem')).toHaveCount(3)
  await expect(claims).toContainText('The post is not public.')
  await page.getByRole('navigation', {name: 'Filter claims'}).getByRole('button', {name: /In review/}).click()
  await expect(claims.getByRole('listitem')).toHaveCount(1)
  expect(app.queries.some(q => q.includes('api/campaign/1/claims?status=pending'))).toBeTruthy()
})

test('a visitor claims a slot with a proof link', async ({page, app}) => {
  await page.goto('/campaign/1'); await app.connect(addresses.council)
  await page.getByRole('textbox', {name: 'Link to your work'}).fill('https://x.com/council/status/9')
  await page.getByRole('button', {name: /^Claim 10/}).click()
  await expect(page.getByRole('status')).toContainText('Claim sent for review')
  expect(app.txs[0]!.messages[0]!.value).toMatchObject({func: 'Claim', args: ['1', 'https://x.com/council/status/9'], caller: addresses.council, pkg_path: `${realmRoot}/campaigns`})
  await expect(page.getByText('Your claim #4 is waiting for a reviewer.')).toBeVisible()
  await expect(page.getByRole('textbox', {name: 'Link to your work'})).toHaveCount(0)
})

test('claimants see their own claim and the poster cannot claim', async ({page, app}) => {
  await page.goto('/campaign/1'); await app.connect(addresses.worker)
  await expect(page.getByText('Your claim #1 was approved and paid.')).toBeVisible()
  await expect(page.getByRole('textbox', {name: 'Link to your work'})).toHaveCount(0)
  await app.setWallet(addresses.reviewer2)
  await expect(page.getByText(/Your claim #3 was rejected: The post is not public\./)).toBeVisible()
  await expect(page.getByRole('textbox', {name: 'Link to your work'})).toBeVisible()
  await app.setWallet(addresses.poster)
  await expect(page.getByText('You posted this campaign.', {exact: false})).toBeVisible()
  await expect(page.getByRole('textbox', {name: 'Link to your work'})).toHaveCount(0)
  expect(app.txs).toHaveLength(0)
})

test('a reviewer approves and rejects claims', async ({page, app}) => {
  app.claims[1]!.push({...app.claims[1]![1]!, number: 4, claimant: addresses.council, proof: 'https://x.com/c/status/4'})
  app.campaigns[0]!.pending = 2; app.campaigns[0]!.claims = 4
  await page.goto('/campaign/1'); await app.connect(addresses.reviewer)
  await expect(page.getByText('You review this campaign. 2 claims are waiting.')).toBeVisible()
  const claims = page.getByRole('list', {name: 'Claims'})
  await expect(claims.getByRole('listitem')).toHaveCount(2)
  await page.getByRole('button', {name: 'Approve claim 2'}).click()
  await expect(page.getByRole('status')).toContainText('Claim 2 approved and paid.')
  expect(app.txs[0]!.messages[0]!.value).toMatchObject({func: 'ApproveClaim', args: ['1', '2'], caller: addresses.reviewer})
  await page.getByRole('button', {name: 'Reject claim 4'}).click()
  await expect(page.getByRole('textbox', {name: "Why it doesn't qualify"})).toBeFocused()
  await page.getByRole('textbox', {name: "Why it doesn't qualify"}).fill('No link to Guildhall in the post.')
  await page.getByRole('button', {name: 'Reject claim', exact: true}).click()
  await expect(page.getByRole('status')).toContainText('Claim 4 rejected.')
  expect(app.txs[1]!.messages[0]!.value).toMatchObject({func: 'RejectClaim', args: ['1', '4', 'No link to Guildhall in the post.']})
  await expect(page.getByText('Nothing waiting for review')).toBeVisible()
})

test('the poster closes a campaign and gets the open slots back', async ({page, app}) => {
  await page.goto('/campaign/1'); await app.connect(addresses.poster)
  await page.getByRole('button', {name: 'Close and refund'}).click()
  await expect(page.getByText('Close this campaign?')).toBeVisible()
  await expect(page.getByText(/980\s*GNOT for the open slots comes back to you/)).toBeVisible()
  await page.getByRole('button', {name: 'Keep it open'}).click()
  expect(app.txs).toHaveLength(0)
  await page.getByRole('button', {name: 'Close and refund'}).click()
  await page.getByRole('button', {name: 'Confirm'}).click()
  await expect(page.getByRole('status')).toContainText('Closed. The open slots were refunded to you.')
  expect(app.txs[0]!.messages[0]!.value).toMatchObject({func: 'Close', args: ['1']})
  await expect(page.getByText('Closed', {exact: true}).first()).toBeVisible()
})

test('posting a native campaign escrows reward × people', async ({page, app}) => {
  await page.goto('/campaigns/new'); await app.connect(addresses.poster)
  await page.getByRole('button', {name: 'Post and fund 0 GNOT'}).click()
  await expect(page.getByRole('alert')).toContainText('Fix the highlighted fields')
  await expect(page.getByRole('textbox', {name: 'Title', exact: true})).toBeFocused()
  await page.getByRole('textbox', {name: 'Title', exact: true}).fill('Write about Guildhall')
  await page.getByRole('textbox', {name: 'What counts'}).fill('A public post that links to guildhall.clockwork.gr.')
  await page.getByRole('textbox', {name: 'Tags'}).fill('social')
  await page.getByRole('textbox', {name: 'Reward per person'}).fill('10')
  await page.getByRole('spinbutton', {name: 'People'}).fill('100')
  await page.getByRole('textbox', {name: 'Reviewers'}).fill(addresses.reviewer)
  await page.getByRole('button', {name: 'Add', exact: true}).click()
  await page.getByRole('button', {name: 'Post and fund 1,000 GNOT'}).click()
  await expect(page).toHaveURL(/\/campaign\/3$/)
  await expect(page.getByRole('heading', {name: 'Write about Guildhall', exact: true})).toBeVisible()
  expect(app.txs[0]!.messages).toEqual([{type: '/vm.m_call', value: {caller: addresses.poster, send: '1000000000ugnot', max_deposit: '', pkg_path: `${realmRoot}/campaigns`, func: 'PostCampaign',
    args: ['Write about Guildhall', 'A public post that links to guildhall.clockwork.gr.', '', 'social', addresses.reviewer, '10000000', '100', '30']}}])
})

test('posting a GRC20 campaign approves the token in the same transaction', async ({page, app}) => {
  await page.goto('/campaigns/new'); await app.connect(addresses.poster)
  await page.getByRole('textbox', {name: 'Title', exact: true}).fill('Translate the docs')
  await page.getByRole('combobox', {name: 'Pay in'}).selectOption(token.key)
  await page.getByRole('textbox', {name: 'Reward per person'}).fill('2.5')
  await page.getByRole('spinbutton', {name: 'People'}).fill('4')
  await page.getByLabel('Stop taking claims after a deadline').uncheck()
  await page.getByRole('button', {name: 'Post and fund 10 GLD'}).click()
  await expect(page).toHaveURL(/\/campaign\/3$/)
  const [approve, post] = app.txs[0]!.messages
  expect(approve!.value).toMatchObject({func: 'Approve', pkg_path: token.key.slice(0, token.key.lastIndexOf('.')), args: [addresses.realm, '1000']})
  expect(post!.value).toMatchObject({func: 'PostCampaignGRC20', args: [token.key, 'Translate the docs', '', '', '', '', '250', '4', '0']})
})

test('a campaign work record links back to its campaign', async ({page, app}) => {
  app.records.push({...record(3), title: 'Write about Guildhall', source: `${realmRoot}/campaigns`, ref: 'c1/1', shareBps: 500, points: 5})
  await page.goto('/record/3')
  await page.getByRole('link', {name: 'Campaign 1'}).click()
  await expect(page).toHaveURL(/\/campaign\/1$/)
})
